### PR TITLE
Add support for Kirby 2.4

### PR DESCRIPTION
**Pull request by flekschas**
Basically only the file name changed.

### CODE REVIEW

**Comment by Pascalmh** [comment]
@flekschas why was this closed? Changes should go into master as they are…

**Comment by Pascalmh** [comment]
And if it is a breaking change it should actually bump the version to 2.0.0 ;)

**Comment by flekschas** [comment]
Sorry for the belated reply. I think my changes were unnecessary that's why I closed the pull request :)

**Comment by Pascalmh** [comment]
@flekschas reopen - they are great :) @flekschas would you mind merging this? This should be Version 2.0.0 though as it breaks current installations by renaming the file…

**Comment by texnixe** [comment]
If the filename is changed, the name in package.json needs to be changed as well, otherwise the plugin will not load when installed via the Kirby CLI.

**Comment by flekschas** [comment]
As much as I would like to contribute I think this pull request is not needed. I think I originally did something like:

```
git submodule add https://github.com/storypioneers/kirby-selector site/plugins/selector
```

This causes troubles as the folder name and file name have to match. I created this pull request and then realized it's not needed if one installs it with:

```
git submodule add https://github.com/storypioneers/kirby-selector site/plugins/field-selector
```

Unless I am missing something I would keep this pull request closed. :)

**Comment by texnixe** [comment]
That's correct, renaming the file wouldn't help any unless you rename the complete repo. It would still add the submodule as kirby-selector unless you specify a path, even if you rename the file.

**Pull request closed without merging**
